[project]
name = "nyc-taxi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Claresta", email = "claresta080@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.1",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "plotly>=6.6.0",
    "prefect>=3.6.23",
    "pyarrow>=23.0.1",
    "python-dotenv>=1.2.2",
    "sodapy>=2.2.0",
    "streamlit>=1.55.0",
]

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
